### ISSUE TITLE
Error occurs when the front camera is selected by default

### ISSUE THREAD

**Issue by ysfm** [TakuSemba/RtmpPublisher#11]
if I select the front camera by default, the application is shutting down.
  
Caused by: java.lang.RuntimeException: setParameters failed
                      at android.hardware.Camera.native_setParameters(Native Method)
                      at android.hardware.Camera.setParameters(Camera.java:1934)
                      at com.takusemba.rtmppublisher.CameraClient.setParameters(CameraClient.java:104)
                      at com.takusemba.rtmppublisher.CameraClient.open(CameraClient.java:36)
                      at com.takusemba.rtmppublisher.RtmpPublisher.onResume(RtmpPublisher.java:100)

**Comment by TapanM** [comment]
getting same issue. Did you find solution?

**Comment by namespace7** [comment]
> if I select the front camera by default, the application is shutting down.
> Caused by: java.lang.RuntimeException: setParameters failed
> at android.hardware.Camera.native_setParameters(Native Method)
> at android.hardware.Camera.setParameters(Camera.java:1934)
> at com.takusemba.rtmppublisher.CameraClient.setParameters(CameraClient.java:104)
> at com.takusemba.rtmppublisher.CameraClient.open(CameraClient.java:36)
> at com.takusemba.rtmppublisher.RtmpPublisher.onResume(RtmpPublisher.java:100)

can you share codes, how are  you trying to do?

**Comment by sunshangqiang** [comment]
getting same issue. Did you find solution?
