### ISSUE TITLE
06-18 04:17:41.217 18491-18594/com.example.admin.maflic E/AndroidRuntime: FATAL EXCEPTION: VideoEncoder-drain

### ISSUE THREAD

**Issue by pavelv99** [TakuSemba/RtmpPublisher#13]
java.lang.IllegalStateException
        at android.media.MediaCodec.releaseOutputBuffer(Native Method)
        at android.media.MediaCodec.releaseOutputBuffer(MediaCodec.java:2424)
        at com.takusemba.rtmppublisher.VideoEncoder$1.run(VideoEncoder.java:127)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pavelv99** [comment]
And one more. 
Caused by: java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:1945)
        at com.takusemba.rtmppublisher.CameraClient.setParameters(CameraClient.java:104)
        at com.takusemba.rtmppublisher.CameraClient.open(CameraClient.java:36)
        at com.takusemba.rtmppublisher.RtmpPublisher.onResume(RtmpPublisher.java:100)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.arch.lifecycle.ClassesInfoCache$MethodReference.invokeCallback(ClassesInfoCache.java:218)
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeMethodsForEvent(ClassesInfoCache.java:193) 
        at android.arch.lifecycle.ClassesInfoCache$CallbackInfo.invokeCallbacks(ClassesInfoCache.java:184) 
        at android.arch.lifecycle.ReflectiveGenericLifecycleObserver.onStateChanged(ReflectiveGenericLifecycleObserver.java:36) 
        at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354) 
        at android.arch.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:292) 
        at android.arch.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:332) 
        at android.arch.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:137) 
        at android.arch.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:123) 
        at android.arch.lifecycle.ReportFragment.dispatch(ReportFragment.java:121) 
        at android.arch.lifecycle.ReportFragment.onResume(ReportFragment.java:88) 
        at android.app.Fragment.performResume(Fragment.java:2554) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1322) 
        at android.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1557) 
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1618) 
        at android.app.FragmentManagerImpl.dispatchMoveToState(FragmentManager.java:3027) 
        at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2989) 
        at android.app.FragmentController.dispatchResume(FragmentController.java:200) 
        at android.app.Activity.performResume(Activity.java:7138) 
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3556) 
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3621) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2862) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 

This is only in 27 api device.

**Comment by Geremp** [comment]
same error.
API 21

**Comment by anupdey99** [comment]
Any solve?
